### ISSUE TITLE
iperf missing from v2.3.0

### ISSUE THREAD

**Issue by vgiotsas** [imunes/imunes#101]
I'm running the VirtualBox for IMUNES v2.3.0 (git: 447d09a) and when I open a router or host interface iperf is missing from the available tools. Is it removed in the newest version? Is there a way to activate it?

By the way, thank you for the excellent tool!

**Comment by denisSal** [comment]
Hi, thank you for your question!

You can install it on all nodes with:
`# pkg_imunes install iperf # FreeBSD`
or
`$ apt-get_imunes install iperf # Linux`.

The package will then be installed in the virtual filesystem. You can do that with any package from the official repositories.

Regards,
Denis

**Comment by vgiotsas** [comment]
Thanks, I didn't know this feature, really useful.
