### ISSUE TITLE
FreeBSD 12.1 "Prepare" Issue

### ISSUE THREAD

**Issue by idahogray** [imunes/imunes#104]
I am having trouble running `imunes -p` on a fresh FreeBSD 12.1 install. The script generates the following output.

```
root@freebsd:~/imunes # imunes -p -f
Unpacking base...
Unpacking base done.
Unpacking lib32...
Unpacking lib32 done.
Installing packages...
Creating repository in /tmp/vroot_prepare/packages/: 100%
Packing files for repository: 100%
Installing packages done.
There were errors installing these packages:
 gnome-themes-extra wireshark firefox xorp sylpheed isc-dhcp44-server ettercap p0f scapy postfix links lighttpd bind913 quagga
Installing additional tools...
Installing additional tools done.
Quagga not installed in /var/imunes/vroot/usr/local/etc/quagga/
Script aborted.
```

I then try to finish the package installation using pkg_imunes which always results in the following message.

`pkg: Cannot open /dev/null:No such file or directory`

I have run `imunes -i` prior to the commands above but that did not change the outcome.

Is there anything else I can try?

**Comment by denisSal** [comment]
Hi, and sorry for the long wait, I've been busy...

Something was changed in the new FreeBSD when chrooting and using `pkg` so we need to mount devfs before installing packages (and unmount it after). This patch should do exactly that when installing IMUNES vroot and when using `pkg_imunes`:
[fbsd121.txt](https://github.com/imunes/imunes/files/5145872/fbsd121.txt)

There are some packages missing (scapy and bind913 - replaced in the new repo with py37-scapy and bind916) but you can install them with the patched `pkg_imunes` as it uses a different repo. You can even upgrade all the packages.

So, download my patch to the `imunes` folder and run:
```
$ cd imunes
$ patch -p1 < fbsd121.txt
$ make install
$ imunes -f -p
$ pkg_imunes install py37-scapy bind916
$ pkg_imunes upgrade # optional
```

This is just a quick patch so I won't be pushing this to master until I test it thoroughly.

Regards,
Denis

**Comment by idahogray** [comment]
Thanks Denis. I reverted to an older FreeBSD version.
