### ISSUE TITLE
Quagga FIB route issues in Freebsd 13.0

### ISSUE THREAD

**Issue by zabel47** [imunes/imunes#110]
I upgraded my imunes environment (OS + vroot) to Freebsd 13.0.
Everything seems to work, but when starting an experiment with quagga dynamic routing (rip or ospf) some of the dynamic routes learned by ospf or rip are not forwarded to the kernel.
For those routing entries you will not find the "FIB" asterisk  in front of the routing entry (sh ip route), but still selected. The routes are missing in the kernel routing table.

In Freebsd 12.2 this still works, the quagga version is no longer maintained in the Freebsd ports tree.
The quagga version installed: 1.2.4_8, Freebsd Version 13.0-RELEASE-p4
Is there a plan to migrate to frr7 instead of quagga to resolve this issue?

**Comment by mmikuc** [comment]
We are aware of the problems with Quagga. It does not work on FreeBSD 13.
Starting with FreeBSD 13, we will replace Quagga with FRRouting (Frr, https://frrouting.org).

The switch is almost trouble-free, but there are some problems with OSPF.
The simplest configuration for OSPF in Quagga does not work under FRR, and the simplest configuration for OSPF in Frr does not work under Quagga.
So there will be some changes in IMUNES that are not yet fully tested and implemented.
(We are looking for an easy way to support old .imn configurations that use OSPF).

In the meantime, you can just use the script for FreeBSD 12 with some changes:

cd imunes/scripts
cp prepare_vroot_12.sh prepare_vroot_13.sh

Edit prepare_vroot_13.sh:

After the line:
PACKAGES_MINIMAL="$PACKAGES_MINIMAL bind916"
insert lines:
PACKAGES_MINIMAL=`echo $PACKAGES_MINIMAL | sed 's/quagga/frr7/'`
PACKAGES_COMMON=`echo $PACKAGES_COMMON | sed 's/lsof//'`

Replace the line:
PACKAGES=`echo $PACKAGES | sed 's/scapy/py37-scapy/'`
with the line:
PACKAGES=`echo $PACKAGES | sed -e 's/scapy/py37-scapy/' -e 's/xorp//'`

Replace the lines
configQuagga
configXorp

with:
mkdir $VROOT_MASTER/usr/local/etc/quagga
configQuagga

And finally, build the vroot:

cd imunes; make vroot
or just call:
imunes -p

Remember that OSPF does not work "out of the box".
