### ISSUE TITLE
Firecracker support

### ISSUE THREAD

**Issue by Dautor** [imunes/imunes#117]
It would be nice to have support for VMs.
This would allow simulation of different operating systems and their interactions.

[Firecracker](https://github.com/firecracker-microvm/firecracker) is a tiny hypervisor with a fairly simple API.
As of recently it supports FreeBSD guests.
Unfortunately, it relies on Linux KVM and does not support FreeBSD as a host operating system yet.

**Comment by denisSal** [comment]
Hi Dautor,

Running this sure feels closer to FreeBSD jails. This could be a great (and faster) alternative for Docker on Linux. I'll explain my thoughts on this in my response to your other issue #118, as both are similar.

Kind regards,
Denis
