### ISSUE TITLE
How can i interact with a lan switch like before with ovs commands?

### ISSUE THREAD

**Issue by alemel03** [imunes/imunes#122]
Now with version 2.4.0 i can't use commands like "ovs-vsctl show". How can i do the same things?

**Comment by denisSal** [comment]
Hi,

Since 2.4.0, IMUNES does not use ovs-vswitch for L2 nodes. You can use `ip link` to get the list of all bridges IMUNES creates. Eventually, we will use network namespaces, so all experiment nodes will be recognized by their own unique netns. 

Denis
