### ISSUE TITLE
Error in 'configureLinkBetween n0 n1 eth0 eth0 IO':can't read 

### ISSUE THREAD

**Issue by jromero17** [imunes/imunes#124]
Good morning, Mr. Denis Salopek, greetings.
It has been a while since I have communicated with you.

This time I do it to inform you that there is an error in the last update of IMUNES that you made, I still can not identify the problem, and I can not find the solution for that update.

I send you the image that I get in the error, it indicates the error. When I try to run the simulation in Execute mode, the error appears.

I updated my repository with your update and now I have the same problem. 

There was a time when I had IMUNES running with frr without problem.

Now the IMUNES in my repository is throwing the same error

I look forward to your response, if you have already got the solution.

![error_ultima_actualizacion_imunes-15-10-2024](https://github.com/user-attachments/assets/cee6ec4c-224a-4844-9b28-93040d5103c4)

EN ESPAÑOL

Buenos días estima señor Denis Salopek, saludos.
A pasado un tiempo que no me comunicaba con usted.

En esta ocasión lo hago para informarle que hay un error en la ultima actualizacion de IMUNES que usted hizo, yo aun no logro identificar el problema, y tampoco consigo dar con la solución para esa actualización.

Le remito la imagen que me sale en el error, ella indica el error. Al intentar ejecuatar la simulación en modo Excecute, aparece el error.

Actualice mi repositorio con su actualización y ahora tengo ese mismo problema. 

Hubo un tiempo que yo tenia funcionando IMUNES con frr sin problema.

Ahora el IMUNES de mi repositorio arroja el mismo error

Quedo atento a su respuesta, si ya ha conseguido la solución.

**Comment by denisSal** [comment]
Please try the latest commit 3df3a4b, it fixes your problem.

Denis
