### ISSUE TITLE
Start through menu not working on Linux

### ISSUE THREAD

**Issue by gcetusic** [imunes/imunes#16]
After stopping a particular node via the menu and then trying to start via the menu "Start" button it produces an error that container isn't started. Docker containers are actually started in createNodeContainer in l3node.instantiate on experiment execution and l3node.start is called AFTER that. But when you call "Start" you don't run instantiate, you skip right to l3node.start which doesn't do much except to exec runConfOnNode on a stopped container. This is why the error happens.

**Comment by oikuda** [comment]
Fixed in ff4e46ddfc0f327e180b42b4738984164a2af6f0.
