### ISSUE TITLE
Docker pull notification

### ISSUE THREAD

**Issue by gcetusic** [imunes/imunes#19]
If IMUNES is run with a specified template for the first time it will take a long time for the first node to start because Docker will automatically be downloading the image if it doesn't exist locally. This makes it seem like IMUNES is stuck. A notification like "Please wait, IMUNES is preparing the filesystem" would be nice...

**Comment by denisSal** [comment]
This is "fixed" in f4fc6edb0f4f7ff6a4c223ca77b51b63af642a41. IMUNES does not automatically pull the Docker image, only notifies the user that it's missing.
