### ISSUE TITLE
Dependency notifications

### ISSUE THREAD

**Issue by gcetusic** [imunes/imunes#22]
LIMUNES depends on several packages to be available:

Docker - service started (for nodes)
Openvswitch - service started (for switches and links)
xterm - on command path (strictly for running terminals on nodes, could become modular in the future)

If ANY of the above doesn't apply, IMUNES should issue a controlled error notifying the user what to do. It has to be done before everything else and atomically because IMUNES could quite possibly create a couple of nodes and then fail or get stuck because e.g. Openvswitch isn't started leaving orphaned containers and/or switches.

**Comment by denisSal** [comment]
Fixed in 6cc1f9d27f5a8c090d824513a105179262d005d4.
