### ISSUE TITLE
IMUNES on Linux: "# imunes -p" command fails

### ISSUE THREAD

**Issue by blinklet** [imunes/imunes#33]
I am trying to set up IMUNES on Ubuntu Linux 14.04. I followed all steps and when I get to the point where I enter the `imunes -p` command, I see the following problem:

    $ sudo imunes -p
    Pulling repository docker.io/imunes/vroot
    2015/07/25 22:25:06 HTTP code: 404

Details:
I am running Ubuntu Server 14.04 with XFCE. I am running my server on Amazon AWS.

**Comment by denisSal** [comment]
I just tried the command, and it downloaded the image successfully. Perhaps the docker servers were down at the time, so you couldn't reach them. (Note to ourselves: maybe we should keep the image on our own server.)

I suggest you try again now and contact us again if it fails.

**Comment by blinklet** [comment]
I tried it again and it still fails. 
Is the URL of the image http://docker.io/imunes/vroot    ?

**Comment by denisSal** [comment]
Try running docker with the debug flag to see more details:
# sudo docker -D pull imunes/vroot:base

Or try downloading any other docker image such as ubuntu:
# sudo docker -D pull ubuntu

I am fairly certain that this has nothing to do with IMUNES (as I am currently able to pull the image). If you cannot access other images, the problem could be your server's firewall/proxy settings.

**Comment by gcetusic** [comment]
Keeping the image on our own server may be more trouble than it's worth because given the resources at Docker's disposal it's more likely our server will fail than theirs. A lot of organizations chose to store their distributions as Docker images on Hub (including Debian, Ubuntu, CentOS, MySQL, PostgreSQL, Redis, Nginx) instead of their own servers. So should we use our own server for a highly customized Docker image not for the general public? YES Use our own server for the generic public template? NO

**Comment by blinklet** [comment]
I tried the docker command and it works but "imunes -p" still fails. Here is what I see:

$ cd imunes
$ sudo imunes -p
Pulling repository docker.io/imunes/vroot
2015/07/28 01:33:14 HTTP code: 404
$
$ sudo docker -D pull imunes/vroot:base
Pulling repository imunes/vroot

53f0f7ad8044: Download complete 902b87aaaec9: Download complete 
9a61b6b1315e: Download complete 
37faa897a236: Download complete 
fa0c720fde2f: Download complete 
374a586ea8f0: Download complete 
b62800543c46: Download complete 
49e969f891e7: Download complete 
$ 
$ sudo imunes -p
Pulling repository docker.io/imunes/vroot
2015/07/28 01:34:57 HTTP code: 404

**Comment by gcetusic** [comment]
@blinklet can you change the docker template uri to just "imunes/vroot:base" in prepare_vroot.sh? Like in this commit: https://github.com/gcetusic/imunes/commit/e3cfc0f961fed855705474d13fde4c56a32a52a9

**Comment by gcetusic** [comment]
@blinklet that commit and the development branch have been merged to master. Please checkout the master branch and try again. Let me know if it's working.

**Comment by blinklet** [comment]
I tried your fix and it worked. Now "imunes -p" works correctly.

Then I started IMUNES and the program hangs up. I thought it might be downloading files but I let it go all night and there was no change. I will investigate some more and open a new issue for the IMUNES startup problem.

I will close this issue. Thanks very much.
