### ISSUE TITLE
IMUNES hangs in Linux

### ISSUE THREAD

**Issue by blinklet** [imunes/imunes#38]
When I start IMUNES in Linux, the GUI starts OK. I add a node (a PC) and execute the experiment. I see the pop-up window that says it is startin the experiment. But it just hangs up at that point.

Here is what I saw when I started IMUNES:

    $ cd imunes
    $ sudo imunes
    [sudo] password for brian: 
    /usr/local/bin/imunes: 80: [: :1.0: unexpected operator

After I start the experiment, the GUI looks like the following:

![screenshot-imunes](https://cloud.githubusercontent.com/assets/11431390/8948520/2de527f6-3576-11e5-9fd9-42184e675fd4.png)

**Comment by gcetusic** [comment]
According to some comments, this could be because we're using sh to run the script with a '==' operator  . Can't reproduce it on my system. @denisSal already fixed this while I was writing this comment :)
@blinklet  Could you try pull and try again?

**Comment by denisSal** [comment]
Hi, thanks for the issue commit!

@gcetusic I just fixed some error checking when starting IMUNES, this should not have anything to do with this bug that happens while starting the experiment.

@blinklet Could you please provide the output of:
`$ sudo docker ps`
`$ ls -lR /var/imunes`

**Comment by gcetusic** [comment]
You're right, the most likely reason for this bug is on this line:
https://github.com/imunes/imunes/blob/master/runtime/linux.tcl#L298

I'm guessing "docker run ..." doesn't execute properly but the exception is catched and after that we're just waiting for it to start even though something went terribly wrong.
@denisSal should we even catch this here? This is a critical point in code and there could be a lot of reasons users can't run docker on their systems, not necessarily related to our Docker image or IMUNES. Not catching the error would help us resolve issues with docker much fast because users could then just paste the error. What do you think?

**Comment by gcetusic** [comment]
@blinklet We've added a printout if imunes is run in debug mode. Could you pull and run "imunes -d" and watch if you get an error in the terminal? We suspect it might be a problem with Docker.

**Comment by blinklet** [comment]
Thanks. I'll try this later tonight.

**Comment by blinklet** [comment]
Hi,

I did the following:

First I ran the docker command suggested by denisSal:

    $ sudo imunes -d
    [sudo] password for brian: 
    /usr/local/bin/imunes: 80: [: :1.0: unexpected operator

Then in another terminal window I run the commands:

    $ sudo docker ps
    CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
    $ ls -lR /var/imunes
    /var/imunes:
    total 20
    drwxr-xr-x 3 root root 4096 Jul 28 23:53 i1bf00
    drwxr-xr-x 3 root root 4096 Jul 28 11:46 i227d0
    drwxr-xr-x 3 root root 4096 Jul 30 02:27 i39500
    drwxr-xr-x 3 root root 4096 Jul 29 00:13 i4c1f0
    drwxr-xr-x 3 root root 4096 Jul 29 00:10 i51df0
    
    /var/imunes/i1bf00:
    total 4
    drwxr-xr-x 2 root root 4096 Jul 28 23:53 n0
    
    /var/imunes/i1bf00/n0:
    total 0
    
    /var/imunes/i227d0:
    total 4
    drwxr-xr-x 2 root root 4096 Jul 28 11:46 n0
    
    /var/imunes/i227d0/n0:
    total 0
    
    /var/imunes/i39500:
    total 4
    drwxr-xr-x 2 root root 4096 Jul 30 02:27 n0
    
    /var/imunes/i39500/n0:
    total 0
    
    /var/imunes/i4c1f0:
    total 4
    drwxr-xr-x 2 root root 4096 Jul 29 00:13 n0
    
    /var/imunes/i4c1f0/n0:
    total 0
    
    /var/imunes/i51df0:
    total 4
    drwxr-xr-x 2 root root 4096 Jul 29 00:10 n0
    
    /var/imunes/i51df0/n0:
    total 0
    brian@ip-172-31-4-94:~/imunes$ 



Next,  I did a git pull, installed IMUNES again and tried everything again:

    $ sudo imunes -d
    'exec docker run' (i8d490.n0) caught:
    flag provided but not defined: --cap-add
    
    Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
    
    Run a command in a new container
    
    -a, --attach=[] Attach to stdin, stdout or stderr.
    -c, --cpu-shares=0 CPU shares (relative weight)
    --cidfile="" Write the container ID to the file
    --cpuset="" CPUs in which to allow execution (0-3, 0,1)
    -d, --detach=false Detached mode: Run container in the background, print new container id
    --dns=[] Set custom dns servers
    --dns-search=[] Set custom dns search domains
    -e, --env=[] Set environment variables
    --entrypoint="" Overwrite the default entrypoint of the image
    --env-file=[] Read in a line delimited file of ENV variables
    --expose=[] Expose a port from the container without publishing it to your host
    -h, --hostname="" Container host name
    -i, --interactive=false Keep stdin open even if not attached
    --link=[] Add link to another container (name:alias)
    --lxc-conf=[] (lxc exec-driver only) Add custom lxc options --lxc-conf="lxc.cgroup.cpuset.cpus = 0,1"
    -m, --memory="" Memory limit (format: <number><optional unit>, where unit = b, k, m or g)
    --name="" Assign a name to the container
    --net="bridge" Set the Network mode for the container
    'bridge': creates a new network stack for the container on the docker bridge
    'none': no networking for this container
    'container:<name|id>': reuses another container network stack
    'host': use the host network stack inside the contaner. Note: the host mode gives the container full access to local system services such as D-bus and is therefore considered insecure.
    -p, --publish=[] Publish a container's port to the host
    format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort
    (use 'docker port' to see the actual mapping)
    -P, --publish-all=false Publish all exposed ports to the host interfaces
    --privileged=false Give extended privileges to this container
    --rm=false Automatically remove the container when it exits (incompatible with -d)
    --sig-proxy=true Proxify all received signal to the process (even in non-tty mode)
    -t, --tty=false Allocate a pseudo-tty
    -u, --user="" Username or UID
    -v, --volume=[] Bind mount a volume (e.g. from the host: -v /host:/container, from docker: -v /container)
    --volumes-from=[] Mount volumes from the specified container(s)
    -w, --workdir="" Working directory inside the container

IMUNES still hangs but it outputs some extra information to the terminal...

Thanks,
Brian

**Comment by denisSal** [comment]
Thanks for your feedback.

You possibly have an older version of docker that doesn't support the flag `--cap-add`. According to [this](https://blog.docker.com/tag/docker-1-2/), they added the flag in version 1.2.0.

Please check your docker version by running:
`$ sudo docker version`
and update docker if necessary.

**Comment by gcetusic** [comment]
If you have an older version of Docker (<1.4) please upgrade to at least 1.3 for basic functionality and at least 1.4 for improved speed.
Which distro and Docker version are you running? Please provide the output of "docker --version".
The add-cap flag was added in Docker 1.2.0 (2014-08-20). An older version of Docker might explain why this fails since some vital components weren't available before Docker 1.3 and the Overlayfs driver which improves the speed of node creation and deletion was added in 1.4.

CHANGELOG:
## 1.4.0 (2014-12-11)
+ New Overlayfs Storage Driver
## 1.3.0 (2014-10-14)
+ Docker `exec` allows you to run additional processes inside existing containers
## 1.2.0 (2014-08-20)
+ `--cap-add` and `--cap-drop` to tweak what linux capability you want

**Comment by blinklet** [comment]
Hi 

I am running Ubuntu Server 14.04 on Amazon AWS with XFCE4. 

I checked the docker version and I see I have an older version

    Client version: 1.0.1
    Client API version: 1.12
    Go version (client): go1.2.1
    Git commit (client): 990021a
    Server version: 1.0.1
    Server API version: 1.12
    Go version (server): go1.2.1
    Git commit (server): 990021a

I will investigate how to install the latest version in 14.04 and let you know how it works

Thanks,
Brian

**Comment by blinklet** [comment]
OK. This fixed the issue. I upgraded to docker 1.7.1 and now IMUNES experiments start and I can log into the virtual nodes and ping across the simulated network.

Thanks for your help!

I will close this issue.
