### ISSUE TITLE
Hub node support in Linux

### ISSUE THREAD

**Issue by gcetusic** [imunes/imunes#39]
There is some template code that in hub.start procedure that show how generally hub supprt should be done. It doesn't work, breaking openvswitch that is supposed to behave like a hub. This is not a critical feature and the Hub node is disabled on Linux for now but would be nice to have it out of the box like in FreeBSD. That's why I'm labelling it as "enhancement".

**Comment by denisSal** [comment]
`ovs-vsctl` has an option to mirror all traffic from multiple ports to one port (I haven't tried multiple ports). Its documentation shows an example:

> Port Mirroring
>       Mirror all packets received or sent on eth0 or eth1 onto eth2, assuming
>       that all of those ports exist on bridge  br0  (**as  a  side-effect  this
>       causes any packets received on eth2 to be ignored**):

```
              ovs-vsctl -- set Bridge br0 mirrors=@m \
              -- --id=@eth0 get Port eth0 \
              -- --id=@eth1 get Port eth1 \
              -- --id=@eth2 get Port eth2 \
              -- --id=@m create Mirror name=mymirror select-dst-port=@eth0,@eth1 \
                   select-src-port=@eth0,@eth1 output-port=@eth2
```

The bold text tells us that it's impossible to implement this functionality with just mirroring.

**Comment by denisSal** [comment]
Enabled hub node in the latest version (>=2.4.0).
