### ISSUE TITLE
Distribute large .ova files via P2P technologies

### ISSUE THREAD

**Issue by bpeden** [imunes/imunes#45]
Hi, just wondering if you would consider releasing an official torrent link as an option for downloading the large ova files available on your website.  As you are probably aware, many projects such as Debian, Arch, and Ubuntu distribute their large files in this manner.

I apologise if this message does not conform to etiquette - I have never submitted an issue before.

**Comment by denisSal** [comment]
Thank you for your suggestion!

You can now find the .torrent file on our [downloads](http://imunes.net/download) section. Please, contact us if you encounter any problems.

We will provide every future .ova file as a torrent as well as a regular download.

Cheers,
Denis
