### ISSUE TITLE
Unclear error message while launching experiment

### ISSUE THREAD

**Issue by KroArtem** [imunes/imunes#53]
Hello, I've downloaded imunes from git, compiled and installed it. Also I installed required dependencies. When I tried to launch a simple case and when I tried to launch an example from examples repo, I got the following error:
![2016-03-08 04-26-58](https://cloud.githubusercontent.com/assets/1813101/13589104/5f1e72bc-e4e6-11e5-9216-29b700762690.png)

However, I've got docker installed and running (1.6.2), ovs-vswitchd is said to be already working, xterm and ncenter are also installed. Is there any way to get some more additional output to understand what's working incorrectly? 

P.S. I forgot to mention I use Ubuntu 16.04, kernel 4.4.0

**Comment by denisSal** [comment]
Hi!

IMUNES checks if docker is running by executing `docker ps` command and checking if its return value is 0 (running) or 1 (error). I recommend that you try running `docker ps` and check its output.

**Comment by KroArtem** [comment]
Hello, thanks for the quick response, `docker ps` said about not having enough privileges. ok, `sudo usermod -aG user` fixed this. Then imunes asked about running it with sudo and after then asked to do `imunes -p` to download docker images. (or it was in another order, first `imunes -p` then request for `sudo`). After this examples load and seem to be working. I have some more questions but will dig into documentation first. :)

Thanks for your help. :) However, I think more precise error message would be good.

**Comment by denisSal** [comment]
You are right, I modified the error messages and added some more details.

Actually, the main problem is that we should first check for sudo rights, and then requisites. I fixed that in edbdefbc152419ed8aed545b46af61c804611f50.

**Comment by KroArtem** [comment]
Thanks!
