### ISSUE TITLE
Experiment list in Linux is deducted by "docker ps" output 

### ISSUE THREAD

**Issue by patriziotufarolo** [imunes/imunes#55]
Hi,
Experiment list in Linux is deducted by `docker ps` output, so experiments that have only switches and no hosts, can't be resumed.
I think that you should read them from /var/run/imunes instead.

**Comment by denisSal** [comment]
Hi!

Thanks for the heads up, we will look into it.

**Comment by patriziotufarolo** [comment]
You are welcome, thank you for having built this software, I'm using it for my Networking Laboratory class!
