### ISSUE TITLE
Imunes doesn't kill/stop docker containers when it's closed

### ISSUE THREAD

**Issue by KroArtem** [imunes/imunes#56]
If you don't stop experiment and exit imunes, it leaves launched containers as they are. It'd be a good idea to check whether experiment is terminated and terminate it or to show a warning message.

**Comment by denisSal** [comment]
Hi!

First of all, you can kill the launched containers by terminating them from the GUI, or by running CLI commands:
```
$ sudo himage -l # list all running experiments
$ sudo imunes -b -e EID # EID = experiment ID you would like to kill
```
OR
```
$ sudo cleanupAll # kill all IMUNES experiments
```

It is possible to attach back to those running experiments with GUI. Just click `Experiment` -> `Attach to experiment` -> `Resume selected experiment`.

So, leaving these containers running is a feature, not a bug. :)

**Comment by KroArtem** [comment]
ok, I see, I just thought a message about containers still running would be good. :)

Feel free to close this ticket.

**Comment by KroArtem** [comment]
One other thing: when I terminate experiment, it's possible to close imunes whilst containers are being stopped and some of them remain working and an error/warning is shown in terminal:
```
invalid command name ".panwin.f1.c"
    while executing
".panwin.f1.c itemconfigure "selectmark || selectbox" -dashoffset $animatephase"
    (procedure "animate" line 5)
    invoked from within
"animate"
    ("after" script)

```

Not that important, though.

**Comment by denisSal** [comment]
I couldn't manage to reproduce this bug, can you please provide more detailed steps for me to try?

**Comment by KroArtem** [comment]
Execute your experiment (I have only 4 nodes in a star), then press to terminate experiment and while there is a small window with "Deleting links and nodes" close imunes itself (main window). I was in a hurry and had to do it, then I noticed docker containers are still up and running. Is it possible to make the main window buttons inactive until experiment is terminated?
