### ISSUE TITLE
Connect nodes with a VM

### ISSUE THREAD

**Issue by danieltdt** [imunes/imunes#59]
Is it possible to connect a imunes' node with a virtualbox machine?
I'm not sure if this configuration is valid, but I'll try to explain it with images:

I'm running imunes on linux (arch) and virtualbox with win7 guest
![imunes-topology](https://cloud.githubusercontent.com/assets/161157/15444656/6beaac0a-1ec9-11e6-88ab-3002cc3ab15b.png)

I've made a bridge network connection between the VM and a port on `switch1` (`n0`)
![vbox-network](https://cloud.githubusercontent.com/assets/161157/15444735/33854efa-1eca-11e6-81e8-8cacf693d956.png)

Then, I've set a valid IP address for this network
![vm-win7-network](https://cloud.githubusercontent.com/assets/161157/15444751/71021e20-1eca-11e6-9bf5-6a3b1be2c5d9.png)

With this configuration, I was able to ping a node (`svr-http`) inside imunes 
![vm-win7-ping](https://cloud.githubusercontent.com/assets/161157/15444757/9f3f75f8-1eca-11e6-85ec-2a042e72933b.png)

But any tcp connection doesn't work properly... It seems that the packages are scrambled
![vm-win7-telnet-80](https://cloud.githubusercontent.com/assets/161157/15444773/dafe59f6-1eca-11e6-9781-50ab30703071.png)

This is the wireshark analysis on `router1`
## ![imunes-wireshark-router](https://cloud.githubusercontent.com/assets/161157/15444780/f7bcfd2c-1eca-11e6-9d63-d8a9d7ff51c5.png)

Am I missing something? I'm not sure if I should create an especial node to make the bridge between VM and Imunes... But the ICMP messages is working anyway...

**Comment by denisSal** [comment]
Hi, thanks for your feedback and sorry for answering so late!

First of all, I guess this _should_ work, but for whatever reason (maybe even openvswitch or VBox interface - I'll check it out), it doesn't. I made the same topology and used Ubuntu as my VM and it connects to telnet/ssh but it takes way too long (at least a minute).

But actually, the proper way to do this is to create an `External connection` node and set its IP and MAC addresses as whatever. This creates an interface on your machine that can than be used as a `Bridged interface` in VBox. (You still need to configure this interface in Windows, of course.)

![imunes](https://cloud.githubusercontent.com/assets/10561979/15465009/8f909c54-20d2-11e6-968b-5f1c9fc9c709.png)

If you have any more questions, don't hesitate to ask.
