### ISSUE TITLE
Wireshark and VNC

### ISSUE THREAD

**Issue by andershagman** [imunes/imunes#63]
When connecting to imunes via VNC you can´t use wireshark from a node.
The app tries to connect to display :0 insted of  :1

root@imunes:/tmp # more startxcmd_i26f00_n0.log
Unable to init server: Could not connect to 127.0.0.1: Connection refused

(wireshark:4877): Gtk-WARNING **: cannot open display: :0.0

**Comment by denisSal** [comment]
Hi, thank you for using IMUNES!

In case you are using FreeBSD, the problem should be solved in c8bac1d. Try again after reinstalling with this update.

**Comment by andershagman** [comment]
Yes i'm using FreeBSD.
Working
thanks
