### ISSUE TITLE
Menus offline

### ISSUE THREAD

**Issue by andershagman** [imunes/imunes#64]
When using big screens "2560x1440" menus show up offline. Is there some kind of maximum resolution defined?

![imunes](https://cloud.githubusercontent.com/assets/20284974/16620089/66747ab6-4391-11e6-9e58-1ffe21eca034.PNG)

**Comment by denisSal** [comment]
What window manager are you using? And what is your FreeBSD version?

I'm not sure if this is a problem with IMUNES or Tcl/Tk. Also, I will need some time to test this on a larger screen because I currently don't have one. :)

**Comment by andershagman** [comment]
Hi

Freebsd 10.3
Xfce4 latest
Via vnc

MHV
/Anders Hagman

**Comment by andershagman** [comment]
It has something to do with tcl/tk and resize in vnc. If I resize the window and then start Imunes, I have no problem. If I start Imunes and then resizes the widows the menus go offline.
You know the problem, I can live with it. ;->
