### ISSUE TITLE
Link parameters issue

### ISSUE THREAD

**Issue by dtudares** [imunes/imunes#65]
Hi, I'm trying to setup a simple topology with a single layer 2 switch and some PCs. I created the topology and it works without any problem, I can ping between the PCs. I tried adjusting some parameters in the link, more specifically, Bandwidth= 100Mbps, Delay=2ms, and after that the Ping doesn't work. If I remove the parameters and test, it works again. Any suggestions? 
I'm using Ubuntu 14.04.5, Docker 1.12.3 and Imunes 2.2.2

**Comment by denisSal** [comment]
Hello!

Can you upload the topology and some captured traffic (while ping does not work)?
I tried what you described on my Arch Linux with the same Docker and Imunes versions, and it works, so I can't be sure what is the problem.

**Comment by dtudares** [comment]
I just realized that the Bandwidth field by default is bps and I was giving 100bps instead of 100Mbps! 
This is embarrassing lol. Thanks anyways, I guess I would not have seen it if you don't ask me for some captures! 
Best regards!

**Comment by denisSal** [comment]
Thank you for the comment, I wish all the bugs would be this easy. 
:)
