### ISSUE TITLE
Attaching a physical interface does not work

### ISSUE THREAD

**Issue by chyouxing** [imunes/imunes#66]
@gcetusic Hi, I have installed imunes on Ubuntu 16.10, the emulation function is very powerful. But I still have two problems.
1. When attaching a physical interface in the emulation scenario, assigning it to an Ethernet port "eth0", and connecting another physical computer with such an Ethernet port, I cannot ping between the physical computer and the virtual router. So could you explain such a configuration process in more detail? Thank you.
2. All items in the "TopoGen" menu are gray, I do not know why.

Thank you in advance.

**Comment by denisSal** [comment]
Hello, thank you for your feedback.

1. Did you configure your other computers IP address and its default route? Nothing else should be configured in IMUNES. If you already did that on your other PC, please send me your .imn file so I can recreate your scenario.

2. TopoGen menu items activate when you select either PC, router or host node beforehand.

**Comment by chyouxing** [comment]
Thank for your answer. There is sth. wrong with my ovs configuration, an I have solved the problem. Now it works well.

**Comment by gcetusic** [comment]
I'm closing this as it was a problem outside IMUNES
