### ISSUE TITLE
Support for BGP and IS-IS via the GUI

### ISSUE THREAD

**Issue by needless** [imunes/imunes#67]
It would be good if IMUNES supported also BGP and ISIS in the GUI. These protocols are already included  in the used quagga version:
![2017-06-30-125537_579x329_scrot](https://user-images.githubusercontent.com/906376/27732976-1575ba62-5d94-11e7-9a7d-999be1c4bf83.png)

But the GUI has no "knobs" to create a working BGP and or ISIS topologies:
![2017-06-30-125831_216x124_scrot](https://user-images.githubusercontent.com/906376/27732999-375fa9c6-5d94-11e7-9008-d60f713c0913.png)

Since these routing protocols are already included in quagga it should be a no-brainer to add it in future releases to the IMUNES GUI.

**Comment by mmikuc** [comment]
Protocol RIP is commonly used in default configuration in which RIP is enabled on all interfaces:
```
router rip
    redistribute static
	redistribute connected
	network 0.0.0.0/0
```
Protocol OSPF can also be used in a simple, default configuration, enabled on all interfaces and with a single area:
```
router ospf
    redistribute static
	redistribute connected
	redistribute rip
	network 0.0.0.0/0 area 0.0.0.0
```
But it can also have a rather complex configuration as in 
[imunes-examples/OSPF/OSPF_RFC.imn](https://github.com/imunes/imunes-examples/tree/master/OSPF "imunes-examples/OSPF/OSPF_RFC.imn") (inspired by "A Sample Au1tonomous System example" in OSPF RFC).

On the contrary, it is difficult to tell what would be the default configuration for protocol BGP.

You can find two examples for BGP in [imunes-examples/BGP](https://github.com/imunes/imunes-examples/tree/master/BGP "imunes-examples/BGP").

In the first one, [BGP-Anycast.imn](https://github.com/imunes/imunes-examples/blob/master/BGP/BGP-Anycast.imn "BGP-Anycast.imn"), BGP router configuration is inserted directly in .imn file.
For example, BGP configuration for node n0:
```
vi BGP-Anycast.imn
...
node n0 {
    type router
    model quagga
    network-config {
	. . .
        router bgp
        router bgp 10000
         no synchronization
         no auto-summary
         network 8.8.8.0 mask 255.255.255.0
         network 9.1.1.0 mask 255.255.255.0
         network 10.10.10.0 mask 255.255.255.252
         neighbor 10.10.10.2 remote-as 22222
        !
```
In the second one, [BGP_custom-config.imn](https://github.com/imunes/imunes-examples/blob/master/BGP/BGP_custom-config.imn "BGP_custom-config.imn"), "Custom Config" feature is used for BGP router's configuration.

Double click on the router or select "Configure" from the right-click popup menu:
- Custom startup config is "Enabled"
- Selected custom config is "conf1"
- Click on "Editor" button

**Comment by needless** [comment]
You are correct of course. Forgot that one needs an working IGP for BGP configuration then the iBGP/EBPG. Sorry my bad. Thanks for the BGP Anycast example that is a really good example, and helps how to use BGP in IMUNES.

In terms of IS-IS it would be nice if there was at least 1 or 2 examples as well. Actually I do not know howto use/configure it in IMUNES in current version, and there is no documentation about this.
1 or 2 really simple examples would help a lot.

**Comment by mmikuc** [comment]
**IS-IS example**

The simple IS-IS configuration is added to [imunes-examples](https://github.com/imunes/imunes-examples "imunes-examples").

Please check that your IMUNES version is at least:
```
# imunes -v
IMUNES v2.2.2 (git: 3083ecb)
Last changed: 2017-07-10 15:46:58 +0200
```
If necessary, update to the newest version:
```
# cd imunes
# git pull
# make remove_vroot
# make install
# make vroot
```

**Comment by needless** [comment]
Thank you for adding the requested examples, and for explaining how to update IMUNES to get the examples working. Acutally I ran into trouble before some days as I was testing  BGP, but after following the update procedure that is mentioned above, all 3 new examples (IS-IS and BGP) have been tested sucessfully over here.

Thanks for putting effort into this. That is really great.
