### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by kfabricni** [imunes/imunes#68]
Hello, 

I've tried to install IMUNES and everything went well except the part where i enter line for the topologies to work (imunes -p). 
I receive this: Error loading package cmdline: can't find package cmdline. 
I did everything that was written in the manual. And also I am using Ubuntu 16.04.2. 

Thank you for your help.

**Comment by denisSal** [comment]
Hi! 

It sounds like you have a problem with your tclsh8.6 installation. Open your terminal and run `tclsh8.6`. 

Then,  execute command: `package require cmdline`. It should print out a version of your cmdline package. If you get an error, something is indeed wrong with your tclsh8.6 installation.

**Comment by kfabricni** [comment]
I did it and it says: "can't find package cmdline". 
Is there any way I could fix this?

**Comment by denisSal** [comment]
This isn't an issue with IMUNES, but with tcllib libraries.

Have you installed tcllib? Can you check where it is located (it should be in /usr/lib/tcllib or something like that)? When you locate it, you should check the `auto_path` global variable to see whether that location is present in the variable:
`# tclsh8.6`
`% puts $auto_path`

**Comment by kfabricni** [comment]
I resolved the issue with reinstalling tcllib and now IMUNES is successfully installed. 

Thank you so much for your time and will to help me. 

Best regards!

**Comment by denisSal** [comment]
Great, happy to help. :)
