### ISSUE TITLE
pkg_add_imunes: pkg_add: not found

### ISSUE THREAD

**Issue by fedegrc** [imunes/imunes#69]
The pkg_add_imunes script of the VMware and VirtualBox images IMUNES-11.0-RELEASE_20170227.ova doesn't work:

[root@IMUNES ~]# pkg_add_imunes 
/usr/local/bin/pkg_add_imunes: pkg_add: not found
[root@IMUNES ~]#

**Comment by denisSal** [comment]
Hi!

```pkg_add_imunes``` uses ```pkg_add``` that works only on FreeBSD 9 and less. For FreeBSD 10+, try using ```pkg_imunes``` (this uses [```pkg```](https://www.freebsd.org/cgi/man.cgi?pkg(7))).

E.g. ```pkg_imunes install wget``` will install ```wget``` to IMUNES virtual root.

**Comment by fedegrc** [comment]
Thank you!
