### ISSUE TITLE
FTP service on Imunes installed on Ubuntu distribution

### ISSUE THREAD

**Issue by federicofranco** [imunes/imunes#70]
Hello
I'm trying to use the service FTP on HOST on Ubuntu 16.10 with dockers and OpenvSwitch (Lubuntu version). I'm using a simple topology with only an HOST called ftp1 and I activated the service ftp and I started the experiment.
I tried to lunch ftp on the HOST ftp1 and I received the error message "command not found."
![immagine](https://user-images.githubusercontent.com/33498402/32573235-95e8877e-c4cd-11e7-9343-f8ec30f68498.png)

The same experiment with Imunes on FreeBSD distribution goes on.
Thank you
Franco

**Comment by denisSal** [comment]
Hi!

We assumed (sorry, that's our fault) that ```ftp``` is installed in docker container by default. Apparently, it isn't.
I will add the ```ftp``` package in the next IMUNES docker image release, but you can locally install ```ftp``` (or any other package) to your own container filesystem by running:
```
sudo apt-get_imunes install ftp
```

**Comment by federicofranco** [comment]
Thank you Denis!
I know the command apt-get_imunes and I will try the work around this night. 
I like to know that I help to fix this problem :)
See you soon
Franco
