### ISSUE TITLE
Enable quagga for SNMP

### ISSUE THREAD

**Issue by EliabCuicas** [imunes/imunes#75]
Good evening folks, I'm a Telecommunications student and I'm doing my degree work on IMUNES. It's really about the SNMP protocol. I am trying to reinstall quagga through the ports to enable the SNMP function, which by default is disabled. I execute the make and make install commands, indicating the following destination address "/var/imunes/vroot/usr/local". However, when you open IMUNES and try to run an experiment, an error occurs and it does not start. Has anyone been able to install quagga with SNMP option? Thank you.

Translated with www.DeepL.com/Translator

**Comment by denisSal** [comment]
Hi Eliab!

Please write some additional information and I will check it out:
1. Which FreeBSD version?
2. Which IMUNES commit?
3. Write all of your commands and outputs (skip the long ones) that lead to this error (starting with building quagga from ports). 

Regards,
Denis

**Comment by EliabCuicas** [comment]
hello denis, sorry for the delay, I'm using freebsd version 11.1 in its 32bits version. The IMUNES version is 2.2.2. I'm using a virtual machine to run freebsd and that's where I have installed IMUNES. I followed your steps, but running step 4. I get the following message: pkg: No packages available to install matching '/usr/ports/net/quagga/work/pkg/quagga-1.2.4_1.txz' have been found in the repositories.

Sorry my English, I'm from Venezuela and I don't know the language very well, so I use a translator to communicate with you, thank you for your time.

**Comment by EliabCuicas** [comment]
Another way I've been trying is to download the quagga code from its official website and compile it. Running the script "configure". Implement the following command: "./configure --enable-snmp --prefix=/var/imunes/vroot/usr/local . However, in the end I get the following message: configure: error: vtysh needs libreadline but was not found and usable on your system.

Even without setting the option "prefix" and executing only the command "./configure --enable-snmp", that error message still appea

**Comment by denisSal** [comment]
Sorry, instead of my step 4, try:
```
# cp /usr/ports/net/quagga/work/pkg/quagga* /var/imunes/vroot
# chroot /var/imunes/vroot
# pkg install /quagga*
```

You cannot configure or make with prefix, this won't work in IMUNES. 

Regards, 
Denis

**Comment by EliabCuicas** [comment]
I did what you told me, but when I run the command "pkg install /quagga*" I get the following error: Updating FreeBSD repository catalogue...
pkg: Repository FreeBSD load error: access repo file(/var/db/pkg/repo-FreeBSD.sqlite) failed: No such file or directory
pkg: http://pkg.FreeBSD.org/FreeBSD:11:i386/quarterly/meta.txz: No address record
repository FreeBSD has no meta file, using default settings
pkg: http://pkg.FreeBSD.org/FreeBSD:11:i386/quarterly/packagesite.txz: No address record
Unable to update repository FreeBSD
Error updating repositories


I thought it had something to do with quagga, but when I run "pkg install nano", I get the same message. I guess it's a repository problem now.

**Comment by denisSal** [comment]
I'm sorry, I'm not at my computer so I forgot the exact command.

Try `# pkg install - U /quagga*`.
This should skip repository checks. 

Regards, 
Denis

**Comment by EliabCuicas** [comment]
Thanks denis, to solve this problem I had to create the file resolv.conf inside the vroot. Then proceeded to run pkg install /quagga* and is already running. Thank you very much for your help, I'll check that QUAGGA was installed with SNMP option and I'll keep you posted. Thank you for your time.

**Comment by EliabCuicas** [comment]
With this command "pkg install -U /quagga*", I'm making sure that the quagga that is going to be installed in IMUNES is the one I gave SNMP support to when I run the "make" command, right? Otherwise, you would be installing a quagga that is downloaded directly from the repositories and which does not have SNMP enabled by default.

**Comment by denisSal** [comment]
Yes, that is correct. But just to be clear, all the steps are:
(0. install net-snmp in vroot if not already installed) 
1. make quagga with SNMP support from ports
2. make quagga .txz package
3. copy the .txz package to /var/imunes/vroot
4. chroot to /var/imunes/vroot 
5. run `# pkg install -U /quagga*`

This installs that package inside the vroot. I hope that's clear now and you got it to work. 

Regards, 
Denis

**Comment by EliabCuicas** [comment]
Clearly, thank you very much for your help and your time. I really appreciate what you have helped me.

Greetings.
