### ISSUE TITLE
installing imunes in freebsd

### ISSUE THREAD

**Issue by EliabCuicas** [imunes/imunes#76]
Good, I downloaded a version of freebsd 11.2 and installed it in a virtual machine (virtualbox), I decided to install IMUNES using the repositories found on this page. However, it gives me a couple of errors.  The first of them after executing the following command: # config VIMAGE

The result is as follows

![virtualbox_imunes-freebsd11](https://user-images.githubusercontent.com/44757807/50133972-55bdd480-0264-11e9-8841-a1b39b9c7901.png)

Aun asi decido continuar con el siguiente paso: # cd ../compile/VIMAGE

para mi sorpresa, el directorio se ha creado, pero al intentar ejecutar los comandos "make", me arroja los siguientes errores:

![2virtualbox_imunes-freebsd11](https://user-images.githubusercontent.com/44757807/50134075-cbc23b80-0264-11e9-9b7a-b6395f0a870b.png)

Igualmente, decido seguir y reiniciar el sistema.

Procedo a ir a la carpeta en donde se encuentran los archivos de IMUNES que descargue de esta pagina y procedo a ejecutar los comandos :

# make install
# imunes -p

Por supuesto, antes de estos descargue los paquetes necesarios para instalar IMUNES: # pkg install tk86 ImageMagick tcllib wireshark socat git gmake

Volviendo al principio, luego de ejecutar "imunes -p" ( y de esperar un largo tiempo), procedo a abrir imunes: # imunes, en modo root.

IMUNES abre, puedo crear cualquier topologia que yo desee, pero al ejecutar el experimento aparece el siguiente error: 
![3virtualbox_imunes-freebsd11](https://user-images.githubusercontent.com/44757807/50134295-ad107480-0265-11e9-8a10-e1f9792e0e59.png)

Of course, I decide to click the "ok" button and proceed to close the experiment by pressing "terminate".
![4virtualbox_imunes-freebsd11](https://user-images.githubusercontent.com/44757807/50134365-f82a8780-0265-11e9-9e0b-9484cb57e0c4.png)
Does anyone have any idea what's going on?

**Comment by denisSal** [comment]
> Good, I downloaded a version of freebsd 11.2 and installed it in a virtual machine (virtualbox), I decided to install IMUNES using the repositories found on this page. However, it gives me a couple of errors. The first of them after executing the following command: # config VIMAGE
> 
> The result is as follows
> 
> ![virtualbox_imunes-freebsd11](https://user-images.githubusercontent.com/44757807/50133972-55bdd480-0264-11e9-8841-a1b39b9c7901.png)

The error tells you where the problem is: you should remove `IPSEC_NAT_T` from your VIMAGE file and try `config VIMAGE` again before installing anything else. (This option is only for some older FreeBSD releases, so it's unnecessary for FreeBSD 11.2)

**Comment by denisSal** [comment]
> I understand, I didn't really think that was the error, I had no knowledge that this line was necessary only for older versions. Where do you get that information?

Official FreeBSD source says: IPSEC_NAT_T option was removed. Now NAT-T support is enabled by default.
So there is no more reason to include that option.

> To run IMUNES I have to do it from the terminal, is there any way to create a shortcut icon on the desktop? 

I don't know which desktop environment you have so I cannot help you with that.

> On the other hand I realize that in the directory /var/imunes/vroot there is no file "rc.conf", I must create it? because for packages like quagga asks me to edit this file with certain lines.
> 
> Thank you for your help.

Quagga works by default in IMUNES, so it's not needed to modify anything. What do you need to add to `rc.conf` and why?

**Comment by EliabCuicas** [comment]
Good morning, I reinstall quagga through the ports to work with the snmp option, after installing it asks me to add the following lines: 

To enable quagga, add the following lines to rc.conf:
defaultrouter="NO"
quagga_enable="YES"

So I think I need to have a "rc.conf" inside of "/var/imunes/vroot."

**Comment by denisSal** [comment]
> Good morning, I reinstall quagga through the ports to work with the snmp option, after installing it asks me to add the following lines:
> 
> To enable quagga, add the following lines to rc.conf:
> defaultrouter="NO"
> quagga_enable="YES"
> 
> So I think I need to have a "rc.conf" inside of "/var/imunes/vroot."

If you installed it and verified that your version is installed, then every IMUNES router node with the quagga model selected in its configuration should run your version without modifying any files.

**Comment by EliabCuicas** [comment]
Okay, I get it. Then wouldn't it be necessary in any case to create a "rc.conf" inside the jail "var/imunes/vroot"?

**Comment by denisSal** [comment]
> Okay, I get it. Then wouldn't it be necessary in any case to create a "rc.conf" inside the jail "var/imunes/vroot"?

No, virtual nodes in IMUNES do not use `rc.conf`, quagga daemons are executed via the `/usr/local/bin/quaggaboot.sh` script.

**Comment by EliabCuicas** [comment]
I wanted to ask some questions about how SNMP works with quagga in IMUNES, I'll open another post. Thank you very much for your patience and help.
