### ISSUE TITLE
Syslog server 

### ISSUE THREAD

**Issue by ArmandoGalea** [imunes/imunes#77]
Syslog Server

Hello, is there any way to enable a syslog on one of the IMUNES computers?
I want to record certain results.

**Comment by ArmandoGalea** [comment]
Hi, don't worry, I hope you had a good vacation.
The way you explain me using a messages file works, but I see that it doesn't record events like lifting or turning off an interface, for example. Happy New Year

**Comment by ArmandoGalea** [comment]
I have a virtualbox image too, the operating system is freebsd 11.2

**Comment by denisSal** [comment]
Interfaces in IMUNES nodes are implemented using `netgraph` kernel module on the host, so that's not visible from the jail.
