### ISSUE TITLE
smux peer

### ISSUE THREAD

**Issue by EliabCuicas** [imunes/imunes#78]
Hello good afternoon, I hope you are well, on this occasion continuous snmp suitable for quagga. I have been following the instructions of the manual of quagga 1.2.0 of the month of March.

I have previously enabled quagga to work with the snmp option and I have installed net-snmp to work with smuxpeer.
![quagga](https://user-images.githubusercontent.com/44757807/50738622-651da700-11ac-11e9-9e93-96d793c94594.png)
![net-snmp](https://user-images.githubusercontent.com/44757807/50738623-6a7af180-11ac-11e9-8f25-2567cdc640ed.png)

However, when I run an experiment on IMUNES, and when I try to start ospfd indicating the configuration file to read, I get the following error.
![smuxpeer](https://user-images.githubusercontent.com/44757807/50738640-b7f75e80-11ac-11e9-9d5c-119da129ace9.png)

Of course, when I try to check the operation of the snmp as indicated in the manual, it does nothing.
![prueba](https://user-images.githubusercontent.com/44757807/50738668-1e7c7c80-11ad-11e9-81b5-fa7e9f58cb8d.png)

The snmpd.conf and ospfd.conf configuration files are as follows: 
![snmpdconf](https://user-images.githubusercontent.com/44757807/50738671-3522d380-11ad-11e9-8263-49b66e1c264c.png)
![ospfdconf](https://user-images.githubusercontent.com/44757807/50738675-4bc92a80-11ad-11e9-807f-a62aec1696b6.png)
Attached I leave the manual by which I'm guided, I hope you can help me, it seems to fit quagga with snmp is more difficult than I expected. Thanks.
[quaggaingles2017.pdf](https://github.com/imunes/imunes/files/2730635/quaggaingles2017.pdf)

**Comment by denisSal** [comment]
According to the attached document, shouldn't the configuration look like this:
```smuxpeer .1.3.6.1.4.1.3317.1.2.5 quagga_ospfd```
instead of:
```smux peer .1.3.6.1.4.1.3317.1.2.5 quagga_ospfd```

(notice the space)

**Comment by EliabCuicas** [comment]
I was thinking that I would enable quagga with snmp according to the post "Enable quagga for SNMP" on this website. In the manual attached basically indicate that it should be enabled like this: "./configure --enable-snmp" within the quagga source code, the latter is downloaded from its official page. However, when executing this command I get the following error.
![configure](https://user-images.githubusercontent.com/44757807/51420843-b8a8d100-1b6c-11e9-92d2-f027f887e5b0.png)
![virtualbox_imunes-freebsd11](https://user-images.githubusercontent.com/44757807/51420851-c9594700-1b6c-11e9-9307-1b74ee8ba99d.png)

Whether using --enable-snmp" or "--enable-snmp=agentx" or "enable-snmp=smux" the result is the same. I think there might be the key to solve this case.

**Comment by EliabCuicas** [comment]
Achieved, really if I had managed to install snmp in quagga and install the agentx, only the latter did not communicate with the demons (zebra, ospfd, ripd, etc..). 

In the snmpd.conf file you have to add the following line:
agentXSocket tcp:localhost:705
