### ISSUE TITLE
vlink script for Linux

### ISSUE THREAD

**Issue by problame** [imunes/imunes#81]
I use imunes to create a container topology for automated testing of an rpc protocol implementation.
Once the topology is created, a test harness runs the rpc server and client on the nodes.
I need to modify link parameters (in particular: delay, up/down) from the test harness, too.

As far as I can tell, this use case is covered with the vlink script for FreeBSD, although it seems rather hacky to jexec into the jail and call ngctl from within.
I tracked down the code that configures the links for open vswitch: https://github.com/imunes/imunes/blob/master/runtime/linux.tcl#L985
That code apparently also runs when modifying link parameters from the GUI while an experiment is running.
Could that code be extracted into a command line script?

Thanks for this great project!

**Comment by denisSal** [comment]
Openvswitch (`tc` manipulating openvswitch links to be exact) is used on Linux, and ngctl is used on FreeBSD so it's not really possible to extract that code to FreeBSD.

And I don't think it's hacky to jexec into jail and call ngctl from within because netgraph interfaces are created inside jails and there is no other way to control them.

**Comment by problame** [comment]
> Openvswitch (tc manipulating openvswitch links to be exact) is used on Linux, and ngctl is used on FreeBSD so it's not really possible to extract that code to FreeBSD.

The code I propose to be re-used by a vlink-rewrite (supporting both Linux and FreeBSD) is https://github.com/imunes/imunes/blob/master/runtime/linux.tcl#L985 , i.e., not the existing vlink script.

**Comment by denisSal** [comment]
I'm pretty sure you are looking at the wrong code... The GUI on FreeBSD calls the procedure `configureLinkBetween` but not the one defined in `linux.tcl` but the one defined in `freebsd.tcl`:
https://github.com/imunes/imunes/blob/master/runtime/freebsd.tcl#L1659

If you were to run IMUNES on Linux, this procedure would be sourced from `linux.tcl` and its GUI would call that on.

**Comment by denisSal** [comment]
At the time it was easier to create a new standalone script without the need to source everything from IMUNES just to get to that specific procedure. :)
