### ISSUE TITLE
RSTP Link and Switch Failures

### ISSUE THREAD

**Issue by MU-MIMO** [imunes/imunes#85]
Is there a way to simulate a physical link or switch failure such that RSTP doesn't rely on the max age timer to determine a failure occurred?  So far I've used "ifconfig ethx down" for a link failure and using the "STOP" feature of IMUNES for a switch failure, both result in the default max age timer of 6 seconds before RSTP begins proposals.

**Comment by denisSal** [comment]
Hello!

You can simulate a link failure in GUI by right clicking on the link and setting the BER (Bit Error Rate) to 1. You can do the same with the `vlink.tcl` CLI command:
```
# vlink.tcl -BER 1 switch1:switch2
```

Notice that in v2.2.2, both `vlink` and `vlink.tcl` tools exist, so make sure you use `vlink.tcl`.

Check `vlink.tcl -h` for other arguments.

Regards,
Denis

**Comment by MU-MIMO** [comment]
Thanks.  I did some testing for link failure and my test network, see attachment, and using "BER" for link failures reduced network downtime for pings but my results are still ~3 seconds.  I expected RSTP to converge and forward traffic less than 1 second for my simple 3 switch setup.  I'll look closer at the BPDU to try and understand why.  If you have any insights please let me know.  As for RSTP parameters I manually set the ports to PCs as edge and ports between switches as point-to-point, switch 1 BR ID = 0, switch 2 BR ID = 4096, switch 3 BR ID = 8192.

**Comment by MU-MIMO** [comment]
Thanks. I did some testing using "BER=1" to simulate a link failure which reduced my network downtime (based on 1s pings) from ~9 seconds to ~3 seconds. However, I expect RSTP to converge and forward traffic in under 1 second for my simple 3 switch setup. I'll look closer at the BPDU to try and understand why, if you have any insights please let me know. As for RSTP parameters I manually set ports to PCs as edge and ports between switches as point-to-point, switch 1 BR ID = 0, switch 2 BR ID = 4096, switch 3 BR ID = 8192.  Other RSTP parameters have been left at IMUNES defaults.
![Capture](https://user-images.githubusercontent.com/49182228/55502941-e13c5500-560a-11e9-9646-cff8ae4914f9.PNG)

**Comment by denisSal** [comment]
I tried this setup, but I don't really think this has anything to do with IMUNES, but with RSPT implementation. Try changing the default settings and playing with different values, maybe that will help. I found that when `Priority` on each switch is set to 36864 (default IMUNES value), I see downtime of less than a second... I can't help you any more than that, I have no experience with RSTP.

**Comment by jleman** [comment]
Do you know who did the RSTP implementation and whether we can contact them?

**Comment by gornjas** [comment]
RSTP support was added to if_bridge in 2006 by Andrew Thompson. IMO, your best chances of getting a response would be subscribing to the net@freebsd.org mailing list and asking implementation-specific questions there. Here's the commit log from FreeBSD:

r163863 | thompsa | 2006-11-01 10:07:47 +0100 (Wed, 01 Nov 2006) | 10 lines

Bring in support for the Rapid Spanning Tree Protocol (802.1w).

RSTP provides faster spanning tree convergence, the protocol will exchange
information with neighboring switches to quickly transition to forwarding
without creating loops. The code will default to RSTP mode but will downgrade
any port connected to a legacy STP network so is fully backward compatible.
