### ISSUE TITLE
Add a new router cisco on imunes with TCL

### ISSUE THREAD

**Issue by simunes** [imunes/imunes#88]
Hi,

I would like to add a Cisco router icon on the toolbox of IMUNES (in left side of the software)(Graphic interface)
I would like to do this by changing or adding some codes in tcl files.
But I have no idea about that.

Can you tell me step by step how can I do that?
Thank you

**Comment by simunes** [comment]
Just I forgot to tell you about my system:
I installed IMUNES Free Bsd On VmWare.

**Comment by denisSal** [comment]
Hello.

Do you need to add a new node with some new functionalities, or just replace the default router one with a custom icon? Or add a new icon that does something else? What would happen if you click on it?

Regards,
Denis
