### ISSUE TITLE
Integrating real hardware into emulated network

### ISSUE THREAD

**Issue by Quixus** [imunes/imunes#90]
I was wondering if it is possible to attach physical hardware to the emulated network.

Thanks in advance for your answer.

Best regards
Quixus

**Comment by denisSal** [comment]
Hello!

Yes, it is possible, and depending on what exactly you need, you can find more information here:
http://imunes.net/dl/guide/node5.html#SECTION00512000000000000000
https://github.com/imunes/imunes/issues/74
https://github.com/imunes/imunes/issues/59
https://github.com/imunes/imunes/issues/48

I suppose you need an `External interface` node to grab one of your physical interfaces and share it with the IMUNES topology. Then, you can connect whatever you want to it and it will be a part of that topology.

In case you need to access from your host PC to the IMUNES topology without 'stealing' your physical interface, you can use the `External connection` node.

**Comment by Quixus** [comment]
My idea was to connect an industrial PC which runs several PLCs to the machine running IMUNES, and then emulate a network the industrial PC will eventually be connected to in order to find out if the nework can fulfil requirements of RTT, throughput etc. 

I will read up on the other topics but I think  chaper 5 of the guide shpuld o the trick. 

Thanks again.
