### ISSUE TITLE
How to NAT on a NAT64 or other router?

### ISSUE THREAD

**Issue by csarp** [imunes/imunes#91]
Please write an example.
I am strungling on this.
I am trying also to assign a public IP on a server inside the private or dmz zone. Any example?

**Comment by denisSal** [comment]
Hi!

Please check out [our examples page](https://github.com/imunes/imunes-examples).

The [DMZ+DNS+Mail+WEB](https://github.com/imunes/imunes-examples/tree/master/DMZ%2BDNS%2BMail%2BWEB) example shows how to run firewall/NAT on a regular router.

**Comment by csarp** [comment]
Hi!
As I can understand the only thing that I can see in the config of each router that runs as a NAT is a static route that sends all traffic to the other interface (on the other side).
The problem occurs when you dont have ip subnets with /24 inside. If you change a node and use a vlsm subnet with /28 /29 or any other there is a problem.
If you change a node to /28 then you have to (somehow) set a gateway to that node.

Also, I cant find any example with VLans. How to configure.

Thank you for your help and for your great work!

**Comment by csarp** [comment]
by the way, I am using the latest VM.
Thank you

**Comment by denisSal** [comment]
> Hi!
> As I can understand the only thing that I can see in the config of each router that runs as a NAT is a static route that sends all traffic to the other interface (on the other side).
> The problem occurs when you dont have ip subnets with /24 inside. If you change a node and use a vlsm subnet with /28 /29 or any other there is a problem.
> If you change a node to /28 then you have to (somehow) set a gateway to that node.
> 

Did you read the [README](https://github.com/imunes/imunes-examples/blob/master/DMZ%2BDNS%2BMail%2BWEB/README) and [PREREQUISITES](https://github.com/imunes/imunes-examples/blob/master/DMZ%2BDNS%2BMail%2BWEB/PREREQUISITES) and did everything written in there? There are scripts in the `DMZ+DNS+Mail+WEB` folder which turn the router into a NAT with `ipfw` commands inside the `start_fw` script.

> Also, I cant find any example with VLans. How to configure.
> 

You need to left click on the `Logical Interfaces` in the `Interfaces` tab of the node and add a new `vlan` interface. There, you configure its physical interface, VLAN tag and IP address.
