### ISSUE TITLE
Changing ip address make the network unreacheable

### ISSUE THREAD

**Issue by csarp** [imunes/imunes#92]
When I change an ip of a host the network is unreacheable.

**Comment by denisSal** [comment]
Hi!

I'm sorry, there is not enough information for me to help you. Please send me a screenshot of your topology and neccessary node configurations.

**Comment by csarp** [comment]
Hi!
I am using the ping example.
You can check also the image with the configs.
[https://ibb.co/QdKxXT6](url)
I am using the latest vm from the site.

Thank you for your help and for your great work!

**Comment by csarp** [comment]
Are there something new on this issue? Am I doing something wrong?

**Comment by denisSal** [comment]
> Hi!
> I am using the ping example.
> You can check also the image with the configs.
> [https://ibb.co/QdKxXT6](url)
> I am using the latest vm from the site.
> 
> Thank you for your help and for your great work!

Your `pc2` subnet is /28, and there are only `2^(32-28)=2^4=16` possible IP addresses in that subnet 10.0.0.0-10.0.0.15. The address 10.0.0.100 cannot be assigned to this subnet so there is an error when adding the default route.

**Comment by csarp** [comment]
ok. If you correct the ip address and choose a (correct) ip address inside the /28 subnet I have the same error.

**Comment by csarp** [comment]
https://ibb.co/hLPYjGG
https://ibb.co/zNL4PrM

**Comment by denisSal** [comment]
Sorry, but you don't seem to understand subnetting and LANs and this issue really has nothing to do with IMUNES. I recommend you research subnets, subnet masks and IP addresses on your own (there are resources about this all over the internet).

**Comment by csarp** [comment]
> > Hi!
> > I am using the ping example.
> > You can check also the image with the configs.
> > [https://ibb.co/QdKxXT6](url)
> > I am using the latest vm from the site.
> > Thank you for your help and for your great work!
> 
> Your `pc2` subnet is /28, and there are only `2^(32-28)=2^4=16` possible IP addresses in that subnet: 10.0.0.0-10.0.0.15. The address 10.0.0.100 cannot be assigned to this subnet so there is an error when adding the default route.

Hi!
Maybe I was not clear enough (or I am wrong somewhere) and I want to apologize for that, but I was a little busy.
Well, 
Lets assume that we have a company with 3 departments and have the 10.0.0.0/24 local network. 
We have a single router with a wan (internet - external public ip).
Lets split the network with VLSM to multiple subnets in order to service the 3 departments (IT, supply, admin).
we will have:
10.0.0.0/27 (for router local interface and future use of the other interfaces)
10.0.0.32/28 (for IT department)
10.0.5.48/28 (from supply department)
10.0.5.64/29 (from admin department)
All the other IPs left for future use.
So, If you place that data to a network inside IMUNES you will get warnings and you will not be able to ping because the network will be unreacheable.
I hope I was clear enough now.
In all your examples you use /24 networks or you use /30 for wan connections (or router connections).
What happens if you split a /24 network to subnets with VLSM **inside** a local lan (one router with multiple subnets with VLSM and not with Fixed Length Subnet Masks)?
Give it a try.
Now here I have to add the gateway matter... How can I add a gateway to a node?
That is my complete question now.
Once more, you have done a great work!

**Comment by denisSal** [comment]
> 10.0.0.0/27 (for router local interface and future use of the other interfaces)
> 10.0.0.32/28 (for IT department)
> 10.0.0.48/28 (from supply department)
> 10.0.0.64/29 (from admin department)
> All the other IPs left for future use.

> Now here I have to add the gateway matter... How can I add a gateway to a node?
> That is my complete question now.

Gateways are added in the `Static routes` field (e.g. `0.0.0.0/0 10.0.0.33`). But, you cannot add a gateway with an IP from a different subnet than your nodes IP. Your router must have:
 1) **one** IP address that covers every IP from every subnet (in your example, I think that's not possible),
 2) **multiple** different IP addresses on one interface (each belonging to every subnet) - this can be done by setting multiple IP addresses in the GUI: `10.0.0.33/25; 10.0.0.49/25; 10.0.0.65/25`.

I tried option `2)` and succeeded (with correct gateways on each PC: 10.0.0.33/25, 10.0.0.49/25 and 10.0.0.65/25):
![image](https://user-images.githubusercontent.com/10561979/66109474-06634d80-e5c5-11e9-9a44-8016741c2236.png)

> Once more, you have done a great work!

Thank you!

**Comment by csarp** [comment]
Hi!
1. Thank you for the info about gateways configuration.

2. About the comment that "I cannot add a gateway with an IP from a different subnet than your nodes IP", I will have to say that this is the case that I wanted the VLANS (multiple vlans with multiple VLSM subnets), in order to have each subnet in a differrent vlan (or/and a pc in more that one vlan). I wanted the isolation on each VLAN. Continuing with VLAN I try to test also to the Switch (that it is a Layer 2 switch) if I can have vlan in the router and in the pc when I have a switch in the middle? Do the switch support pass-through encapsulation? I was experimenting with vlan (the manual does not have any how to) and I could not succeed with isolation, so I dont know if that test was a success. 
Just imagine an example that every department (IT, supply, admin) must be in different VLAN and only IT must see/ work/ ping on all VLANs. The other departments (supply, admin) can ping to the host or the routers (the interface of the router that have the vlan ip of course) but not each other. 
I tried that without success. I thing that I am confusing something in the configuration... An example would be better.

3. About the third part of your answer about "multiple different IP addresses on one interface" I have to say that it is very helpful and practical (I could not find any info and example about that).

Kind Regards
Christos

**Comment by gornjas** [comment]
Hi Christos,

sorry for jumping in this thread but I find it difficult to follow your questions which seem to be vague, and rely on vague terms (what exactly does "pass-through encapsulation support" mean?).

One of the main features in IMUNES is that one can export / share the topology configuration as a single file. As Denis mentioned earlier in this thread, and you echoed it yourself ("An example would be better"), it would be much easier to help you had you attached a .imn file corresponding to your experiment, and then asked focused questions with easy-to-reproduce steps related to that particular example, instead of engaging in a broad range of hypothetical what / if elaborations.

**Comment by csarp** [comment]
Thank you for your answers.
About the switch, my question is if that switch module can support vlan's pass through? As I can see the switch is unmanaged layer 2 so how can I configure the vlans in the ports (e0, e1, ...) and pass from thaat ports the correct vlan packet to the correct port?
I try the imunes with small examples to see if I can use it as other simulations. So I dont have a ready made network topology.
As I can see in the examples there are no examples for vlans.

**Comment by csarp** [comment]
Please consider the thread as solved/ closed. Thank you for your answers.
