### ISSUE TITLE
Name is not a valid ifname

### ISSUE THREAD

**Issue by bauen1** [imunes/imunes#95]
Somewhat large project, but the problems is that the ifnames are too long

```
Error: argument "i1043ea0-n4-eth1" is wrong: "name" not a valid ifname
Error: argument "i1043ea0-n4-eth1" is wrong: "name" not a valid ifname
    while executing
"exec ip link add name "$hostIfc" type veth peer name "$guestIfc""
    (procedure "addNodeIfcToBridge" line 13)
    invoked from within
"addNodeIfcToBridge $lname2 $ifname2 $lnode1 $ifname1 $ether1"
    ("VIMAGE-NETGRAPH" arm line 2)
    invoked from within
"switch -exact "[[typemodel $lnode1].virtlayer]-[[typemodel $lnode2].virtlayer]" {
	NETGRAPH-NETGRAPH {
	    if { [nodeType $lnode1] == "ext" } {
		cat..."
    (procedure "createLinkBetween" line 28)
    invoked from within
"createLinkBetween $lnode1 $lnode2 $ifname1 $ifname2"
    (procedure "deployCfg" line 131)
    invoked from within
"deployCfg"
    (procedure "setOperMode" line 74)
    invoked from within
"setOperMode exec"
    invoked from within
".#menubar.#menubar#experiment invoke active"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke active]"
    (procedure "tk::MenuInvoke" line 50)
    invoked from within
"tk::MenuInvoke .#menubar.#menubar#experiment 1"
    (command bound to event)
```

Work around: specify a small experiment id using `-e`

The issue is that the ifname is simply too long, e.g. compare the output of:
```bash
$ ip link add i1043ea0-n4-eth1 type dummy
```
to
```bash
$ ip link add i1043ea0-n4 type dummy
```

**Comment by oikuda** [comment]
Hello,

Thanks for the detailed report, I've noticed the same happens with long interface names when starting the topology.
Your workaround for now is the best way to handle this. I'll try and find a good fix so that it doesn't occur anymore.

Cheers!

**Comment by oikuda** [comment]
Please try out the above commit and see if its a good workaround for your case.
There are two possible long-term (way more complex) solutions to this problem:
- separating namespaces for eids in Linux, like it's done in FreeBSD
- creating separate naming conventions and ids and keeping track of them in the runtime dir.

**Comment by oikuda** [comment]
I forgot to include the issue number in the latest commit, please use 719684a for testing.
